
cursor            #f9bb72
cursor_text_color #472a00

foreground            #eee0d5
background            #130d07
selection_foreground  #3f2d17
selection_background  #dfc1a2
url_color             #dfc1a2

#: black 000000 767676
color0  #18120c
color8  #3b332c
#: red cc0403 f2201f
color1  #485e7e
color9  #9aacc5
#: green 19cb00 23fd00
color2  #dfc1a2
color10 #fdddbd
#: yellow cecb00 fffd00
color3  #bccd9d
color11 #d8e9b8
#: blue 0d73cc 1a8fff
color4  #663e00
color12 #f9bb72
#: magenta cb1ed1 fd28ff
color5  #58432b
color13 #dfc1a2
#: cyan 0dcdcd 14ffff
color6  #3d4b27
color14 #bccd9d
#: white dddddd ffffff
color7  #d4c4b5
color15 #eee0d5

mark1_foreground #2b1700
mark1_background #ffddb9
mark2_foreground #281805
mark2_background #fdddbd
mark3_foreground #131f02
mark3_background #d8e9b8

active_tab_foreground #472a00
active_tab_background #f9bb72
inactive_tab_foreground #ffddb9
inactive_tab_background #663e00

active_border_color #f9bb72
inactive_border_color #472a00
# bell_border_color #ff5a00
