
cursor            #88d0ec
cursor_text_color #003544

foreground            #dee3e6
background            #0a0f11
selection_foreground  #1e333c
selection_background  #b3cad5
url_color             #b3cad5

#: black 000000 767676
color0  #0f1416
color8  #303638
#: red cc0403 f2201f
color1  #1e2529
color9  #5f7381
#: green 19cb00 23fd00
color2  #b3cad5
color10 #cfe6f1
#: yellow cecb00 fffd00
color3  #c4c3eb
color11 #e1e0ff
#: blue 0d73cc 1a8fff
color4  #004d61
color12 #88d0ec
#: magenta cb1ed1 fd28ff
color5  #354a53
color13 #b3cad5
#: cyan 0dcdcd 14ffff
color6  #434465
color14 #c4c3eb
#: white dddddd ffffff
color7  #bfc8cc
color15 #dee3e6

mark1_foreground #001f29
mark1_background #b8eaff
mark2_foreground #071e26
mark2_background #cfe6f1
mark3_foreground #171837
mark3_background #e1e0ff

active_tab_foreground #003544
active_tab_background #88d0ec
inactive_tab_foreground #b8eaff
inactive_tab_background #004d61

active_border_color #88d0ec
inactive_border_color #003544
# bell_border_color #ff5a00
