
cursor            #b8c4ff
cursor_text_color #1f2c61

foreground            #e3e1e9
background            #0d0e13
selection_foreground  #2c2f42
selection_background  #c2c5dd
url_color             #c2c5dd

#: black 000000 767676
color0  #121318
color8  #34343a
#: red cc0403 f2201f
color1  #535e8d
color9  #abb2ce
#: green 19cb00 23fd00
color2  #c2c5dd
color10 #dfe1f9
#: yellow cecb00 fffd00
color3  #e4bad9
color11 #ffd7f4
#: blue 0d73cc 1a8fff
color4  #374379
color12 #b8c4ff
#: magenta cb1ed1 fd28ff
color5  #424659
color13 #c2c5dd
#: cyan 0dcdcd 14ffff
color6  #5c3d56
color14 #e4bad9
#: white dddddd ffffff
color7  #c6c5d0
color15 #e3e1e9

mark1_foreground #07164b
mark1_background #dde1ff
mark2_foreground #171b2c
mark2_background #dfe1f9
mark3_foreground #2c1229
mark3_background #ffd7f4

active_tab_foreground #1f2c61
active_tab_background #b8c4ff
inactive_tab_foreground #dde1ff
inactive_tab_background #374379

active_border_color #b8c4ff
inactive_border_color #1f2c61
# bell_border_color #ff5a00
